<?php
$parties = array(
  1 => "VVD",
    "PvdA",
    "PVV",
    "SP",
    "CDA",
    "D66",
    "ChristenUnie",
    "GroenLinks",
    "SGP",
    "Partij voor de Dieren",
    "50PLUS",
    "OndernemersPartij",
    "VNL",
    "DENK",
    "Nieuwe Wegen",
    "Forum voor Democratie",
    "De Burger Beweging",
    "Vrijzinnige Partij",
  20 => "Piratenpartij",
    "Artikel 1",
    "Niet Stemers",
    "LP",
    "Lokaal in de Kamer",
    "JEZUS LEEFT",
    "StemNL",
    "MenS en Spirit",
    "VDP");

$themes = array(
  "Zorg",
  "Europese Unie",
  "Veiligheid",
  "Migratie",
  "Defensie",
  "Financi&euml;n",
  "Economische Zaken",
  "Infrastructuur",
  "Milieu",
  "Onderwijs",
  "Cultuur",
  "Sociale Zaken",
  "Sport",
  "Binnenlandse Zaken",
  "Buitenlandse Zaken");
?>